### ISSUE TITLE
lifecycle-hooks-challenge branch contains solution

### ISSUE THREAD

**Issue by tkilgour** [netlify/explorers-composition-api#5]
The `lifecycle-hooks-challenge` branch already contains the solution and the expected solution branch (`lifecycle-hooks-solution` does not exist.

Thanks for a great little walkthrough of the composition api!

**Comment by bencodezen** [comment]
Thanks for filing the issue @tkilgour! I'll get that fixed pronto

**Comment by bencodezen** [comment]
We should be good now. Let me know if you still see the issue! Thanks for letting me know!
